### ISSUE TITLE
献立のレパートリーのテーブルを作成する

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#1]
## テーブル名に献立のレパートリー(cooking_repertoires)を作成する
1.モデル作成（モデル名: cooking_repertoire)
2.マイグレーションファイルにテーブルを追加

**テーブル名: cooking_repertories**
|Column|Type|Option|
|-----|-----|-----|
|name|string|null: false, unique: true|

## 完了条件
**cooking_repertories**のテーブルを作成できる。以下のような構成
|id|name|created_at|updated_at|
|-----|-----|-----|-----|
||||

**Comment by ShioriKato** [comment]
一意制約必要かも

**Comment by takuminasu** [comment]
修正しました。
