### ISSUE TITLE
新規登録機能の実装

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#2]
## 新規登録機能の実装
~~1.一覧画面に新規登録リンクを作成~~
2.newアクションを実装
3.新規登録画面のビューの実装
4.createアクションの実装(作成に成功すると新規登録画面にリダイレクト)

## 完了条件
データベースにデータを保存することができる

**Comment by lx-ishida** [comment]
この時点で一覧画面は未作成のはずなので 4 の後は新規登録画面に遷移で良いです
登録するとアラート「○○を登録しました」などが表示され、登録元（いま）の画面に戻るイメージです
一覧画面作成のissueで遷移先を変更してください

**Comment by takuminasu** [comment]
修正しました。
