### ISSUE TITLE
献立作成時に候補になったタグを保存するテーブルを作成する

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#25]
refs #26 
## 概要
- 献立作成時に献立の候補になったタグを保存するテーブルを作成する
  - モデルを作成する(model名: MenuCandidateTag)
  - マイグレーションファイルにカラム情報を記述する

DB情報
|column|type|option|
|-----|-----|-----|
|tag_id|integer|null: false, foreign_key: true|

## 完了条件
- モデルが作成されている
- DBが更新されている

以下のようなテーブル構成
|id|tag_id|created_at|updated_at|
|-----|-----|-----|-----|
|1|1|2020-05-13|2020-05-13|
|2|2|2020-05-13|2020-05-13|
|3|3|2020-05-13|2020-05-13|
|:|:|:|:|:|

**Comment by lx-ishida** [comment]
具体的にどういうデータが登録されることを想定していますか？？

**Comment by takuminasu** [comment]
~除くタグをチェックする際に
中華(tag_id = 3)をチェックして献立作成ボタンを押した時~
初めは全てにチェック済み
献立作成から除く場合チェックを外す
中華(tag_id = 3)を除いて献立作成した場合

|id|tag_id|valid|created_at|updated_at|
|-----|-----|-----|-----|-----|
|1|1|true|2020-05-13|2020-05-13|
|2|2|true|2020-05-13|2020-05-13|
|3|3|false|2020-05-13|2020-05-13|
|:|:|:|:|:|

上記のようなデータが入ることを想定しています。

**Comment by lx-ishida** [comment]
> 献立作成時に作成から除くタグを保存するテーブル

作成から除かないタグも保存するわけなので、テーブルの名前がちょっとおかしいかな？
model名は名詞で

---

- valid の type（型）は string ではなく他の型が良いのでは？

---

あとは view を作るときのことをちょっと意識しながら考えて欲しく

使う側（ここでは奈須さんになりますが笑）がぱっと見てわかりやすいのは、
`除くタグ` なのか `献立候補のタグ` なのか、など

valid: true は `除く` が有効になるのか、`候補になる` なのか？
この時点ではっきりしておいた方が良いなと思いました

※はっきり整理できてれば特に問題はない

**Comment by takuminasu** [comment]
タグが有効かどうかの状態を保存するテーブルなので
model名は**TagStatus**にしようと思います。

viewの時に`献立候補のタグ`の方がパッと見てわかりやすいと思いました。
なのでvalid: trueは`候補になる`です

**Comment by lx-ishida** [comment]
```
viewの時に献立候補のタグの方がパッと見てわかりやすいと思いました。
なのでvalid: trueは候補になるです
```
とすると、`献立候補のタグ`テーブルなので、直訳で`menu_candidate_tags`などの方がわかりやすい名前になりそう

その場合、`候補になったタグ`のみ管理していれば良いので、`validity`カラムは不要になる
