### ISSUE TITLE
一覧表示機能の実装

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#3]
## 一覧表示機能の実装
1.indexアクションでデータを取得する
2.一覧表示画面でデータ(name, ~~created_at~~)を表示する

## 完了条件
一覧表示画面でデータ(name,~~created_at~~)の表示ができる

**Comment by lx-ishida** [comment]
`created_at` の表示は必要？

**Comment by takuminasu** [comment]
必要ないです。修正しました。
