### ISSUE TITLE
レパートリー新規登録(編集)時、タグの個数にバリデーションをかける

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#32]
## レパートリー新規登録(編集)時、タグの個数にバリデーションをかける
1.レパートリー名、タグに必須マークをつける　※必須マークをつけることは必須ではない
2.ビューに補足情報を加える
・複数選択可、3つまで
3.レパートリーの新規登録/編集の際にバリデーション(保存できるタグ1~3個)をかける
4.バリデーションに引っかかったらエラーメッセージを表示する
　・タグを選択せずに保存しようとした時
　・タグを4個以上で保存しようとした時
## 完了条件
新規登録/編集の際にバリーデーションをかけることができる
レパートリー名につけるタグが0個または4個以上の状態で保存しようとした時にエラーメッセージを表示する

**Comment by lx-ishida** [comment]
- タグの個数にバリデーションをかける必要があるか検討した方が良いかもしれません
- タグを3つ設定してあるレパートリーを削除しようとすると予期しないバリデーションエラーになりそう

**Comment by takuminasu** [comment]
>・タグの個数にバリデーションをかける必要があるか検討した方が良いかもしれません

前後被らない日数を設定する機能を実装する時に基準がレパートリー名だと例えば連続で中華が決まる可能性があるのでタグを基準にしようと思っています。
極端ですがもしタグを全て選択して保存するとそのレパートリーは一度も選ばれません。
なのでバリデーションをかける必要があると思いました。

>・タグを3つ設定してあるレパートリーを削除しようとすると予期しないバリデーションエラーになりそう

onオプションでバリデーション実行のタイミングを指定して(create, update)レパートリー削除時はバリデーションをかけないように実装しようと思うのですがどうでしょうか？

参考記事: https://railsguides.jp/active_record_validations.html#on
