### ISSUE TITLE
レパートリーの削除機能を実装する

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#34]
refs #35 
## 概要
※レパートリー詳細に削除ボタンは実装済み #6 
- ルーティングを実装する (cooking_repertoire_tags#create)
- 削除処理を実装する(controller)
  - 対象のレパートリーに削除タグを追加する (model)
  - レパートリー一覧に遷移する&フラッシュメッセージを表示する
- すでに3つタグを持つデータでも保存できるようにする(model)
  - タグの個数制限（1〜3）を Tag model に定義済み
## 完了条件
- レパートリー詳細を表示した際、削除ボタンをクリックできること
- 削除ボタンをクリックすると、レパートリー一覧に遷移し削除した旨のフラッシュメッセージが表示されること
- 既に3つのタグを持つレパートリーも削除できること
- 削除処理が完了した際、cooking_repertoire_tags テーブルに対象のレパートリーIDとタグID（消去）を持つレコードが登録されていること

**Comment by lx-ishida** [comment]
refs #35 

- 関連するissueの作業がある場合、↑のように詳細欄に記載するようにしてください
（`＃issue番号` があれば `refs` はあってもなくても良い）
- `削除` なのか `消去` なのか文言は統一すべき
- `やること` と `その詳細` はなるべく分けて記載するようにするとわかりやすいかもれません
  - 階層をうまく使えるともう少し整理できるかも

**Comment by lx-ishida** [comment]
以下、例
---

# レパートリーの削除機能を実装する（※タイトル）

## 概要
※ルーティングは既に実装済み（`＃issue番号`）

- レパートリー詳細に削除ボタンを追加する（view）
- 削除処理を実装する（controller）
  - 対象のレパートリーに `削除` タグを追加する（model）
  - レパートリー一覧に遷移する & フラッシュメッセージを表示する（controller, view）
- 既に3つタグを持つデータでも `削除` タグを保存できるようにする（model）
  - タグの個数制限（1〜3）を Tag model に定義済み

## 完了条件

- レパートリー詳細を表示した際、削除ボタンをクリックできること
- 削除ボタンをクリックすると、レパートリー一覧に遷移し削除した旨のフラッシュメッセージが表示されること
- 既に3つのタグを持つレパートリーも削除できること
- 削除処理が完了した際、cooking_repertoire_tags テーブルに対象のレパートリーIDとタグID（削除）を持つレコードが登録されていること

---

※（model, view, controller）の記載は不要ですが、issue作成してる際に少々混乱してそうな印象を受ける点があるので慣れるまでは明記すると良いかな？と思いました

**Comment by takuminasu** [comment]
tagsのテーブルを作成する時に名前を消去にしてしまいました。
削除を使うことが多いので削除に統一したいと思うのですが別のissueを作成して対応した方がよろしいでしょうか？

例を書いてくださりありがとうございます。
参考にしながら修正します。

**Comment by lx-ishida** [comment]
> tagsのテーブルを作成する時に名前を消去にしてしまいました。
削除を使うことが多いので削除に統一したいと思うのですが別のissueを作成して対応した方がよろしいでしょうか？

これは別issueにしましょう

**Comment by takuminasu** [comment]
承知しました。
