### ISSUE TITLE
bootstrapの導入

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#37]
## 概要
- bootstrapを導入する
  - yarn add でjQuery, bootstrap, popper.jsを加える
  - webpackの設定でProvidePluginを加える
  - application.cssファイルをapplication.scssにファイル名を変更する
    - ファイルの中身は削除して以下のコードを記述する
```
@import '~bootstrap/scss/bootstrap';
```

  - application.jsに以下のコードを記述

```
import 'bootstrap';
import '../stylesheets/application';
```

  - app/views/layouts/application.html.slimに以下のコードを記述する

```
= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
```

## 完了条件
- webpackerを利用してbootstrapを導入できている

**Comment by lx-ishida** [comment]
gem ではなく webpacker を利用して bootstrap を追加してみてください
