### ISSUE TITLE
レパートリー名の詳細のスタイル適用

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#40]
## 概要
- レパートリー詳細画面のスタイルを適用する
  - bootstrapを用いて詳細画面にスタイルを適用する
    - 詳細の左の"<"はタグ一覧画面に戻る
    - tableで実装する
  - scssファイルを使うときはpxではなくremを用いる
## 完了条件
<img src="https://user-images.githubusercontent.com/62975075/82523442-3ae14500-9b67-11ea-9ce3-3c9aef400283.jpeg" width="320px"/>

**Comment by lx-ishida** [comment]
> scssファイルを使うときはpxではなくremを用いる

基本的にはフォントサイズだけで大丈夫です
最初はmargin, padding まで em, rem 使うとわけわからなくなるので。
もちろん理解できていれば使っても大丈夫です
