### ISSUE TITLE
編集機能の実装

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#5]
## 編集機能の実装
1.~~一覧画面と~~詳細画面に編集ボタンを実装する
2.edit, updateアクションを実装
3.パーシャルを用いて新規登録画面と編集画面の共通化

## 完了条件
データベースのデータの情報の編集ができる

**Comment by lx-ishida** [comment]
一覧画面に編集ボタン必要？

**Comment by takuminasu** [comment]
必要ないです。修正しました。
