### ISSUE TITLE
ルーティングの修正

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#50]
## ルーティングの修正
1.localhost:3000にアクセスした時にmenus/indexに飛ぶように修正
2.不必要なルーティングの削除(cooking_repertoires :index, menus :show)
3.適切なページに飛ぶようにリンクを修正する

## 完了条件
下記のようなルーティングになっている
![image0 (5) (1)](https://user-images.githubusercontent.com/62975075/80689648-98eeaf80-8b08-11ea-9fdc-5988b93a4609.jpeg)

**Comment by lx-ishida** [comment]
`cooking_repertoires :index` がトップになるので必要では？

**Comment by takuminasu** [comment]
下記のようなビューの割り当てになるのでmenus/indexがトップになります。
![image0 (7)](https://user-images.githubusercontent.com/62975075/81252747-a9031380-9061-11ea-816f-d4a955ca331b.jpeg)
