### ISSUE TITLE
tagsテーブルのnameが消去のレコードを削除に変更

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#56]
refs #14 
## 概要
- 消去なのか削除なのかややこしいので削除に統一する(db)
  - seed.rbの{name: '消去'}を{name: '削除'}に変更
  - ja.ymlファイルの消去を削除に変更する
- dbを更新する(db)
  - rails db:migrate:reset と rails db:seedでdbを更新する(レパートリーや献立は削除される)

## 完了条件
- seeds.rbとja.ymlファイルが削除に統一されている
- tagsテーブルのname: 消去がname: 削除に更新されている

**Comment by lx-ishida** [comment]
もう少し具体的な作業内容を記載して欲しい
