### ISSUE TITLE
削除タグがついているレパートリーは除いて献立を作成する

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#58]
## 概要
※献立作成機能は実装済み #23 
- 献立作成時に削除したレパートリーは除く実装(model)
  - 削除タグがついているレパートリーを取得する(model)
  - 取得したレパートリーを除くレパートリー (= 削除タグがついていないレパートリー)を取得する(model)
- 取得したレパートリーの中からランダムで一つ取得し献立を作成する。※実装済み

## 完了条件
- 削除タグがついているレパートリーは除いて献立が作成できる

**Comment by lx-ishida** [comment]
> - 献立作成時に削除したレパートリーは除く実装(model)
>   - cooking_repertoiresテーブルとtagsテーブルを結合して削除タグがついているレパートリーを取得する(model)
>   - 取得したレパートリーを除くレパートリー (= 削除タグがついていないレパートリー)を取得する(model)

一旦分けて考え実装しても良いです
（が、1回のクエリでできそうではあるので、分けての実装ができた後、時間があれば試してみて欲しい）

```
cooking_repertoiresテーブルとtagsテーブルを結合して
```
この文で混乱しそうなので、なくても良い（伝わる）と思う
