### ISSUE TITLE
削除機能の実装

### ISSUE THREAD

**Issue by takuminasu** [takuminasu/todays_dinner#6]
## 削除機能の実装
1.~~一覧画面と~~詳細画面い削除ボタンを実装
2.destroyアクションを実装(削除後一覧表示にリダイレクト)※実際にデータを削除はしない

## 完了条件
~~データベースのデータを削除できる~~
http のリクエストが delete で動作している
リダイレクト処理ができている

**Comment by lx-ishida** [comment]
- 一覧画面に削除ボタン必要？
- 削除はタグ付で対応する予定では？（タグ機能が実装されるまでこのissueは保留？）

**Comment by takuminasu** [comment]
CRUDアプリの作成なのでdestroyのアクションも必要なのかと思いました。
研修用アプリベースで考えるならdestroyアクションがないです。

**Comment by lx-ishida** [comment]
メソッド（枠）を作成して内容は別issueで対応
http のリクエストが delete で動作していることの確認とリダイレクト処理だけ実装する

**Comment by takuminasu** [comment]
`メソッド（枠）を作成して内容は別issueで対応`
-メソッドは作成して別issueで対応。承知しました。
`http のリクエストが delete で動作していることの確認とリダイレクト処理だけ実装する`
-自分の理解不足で申し訳ありません。この文はrails cで確認するということでよろしいでしょうか？

**Comment by lx-ishida** [comment]
ちょっと研修の順番前後してしまって申し訳ないですが

---

削除クリックしたときのリクエストのログを確認（rails s で実行中に流れるやつ）
こんな感じの
```
Started GET "/xxxx" for 127.0.0.1 at 2020-04-14 04:43:31 +0000
Processing by XxxxController#index as JSON
  Parameters: {"xxx"=>["xxx"]}
  Xxx Load (4.6ms)  SELECT  `xxx`.* FROM `xxx` WHERE `xxx`.`deleted_at` IS NULL LIMIT 1
```
`GET` 部分が `DELETE` になっているはず

**Comment by takuminasu** [comment]
理解しました。
実行結果に削除をクリックした際のログを添付すればいいということですか？

**Comment by lx-ishida** [comment]
それでお願いします！
